repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code with cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code with clippy
        entry: cargo clippy --all-targets --all-features -- -W clippy::missing_panics_doc
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        description: Run tests
        entry: cargo test --all-features
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-audit
        name: cargo audit
        description: Check for security vulnerabilities
        entry: cargo audit
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-push]
