repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code with cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        description: Check code compilation
        entry: cargo check --all-targets --all-features
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code with clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        description: Run tests
        entry: cargo test --all-features
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-doc
        name: cargo doc
        description: Build documentation
        entry: cargo doc --no-deps --all-features
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-push]

      - id: cargo-audit
        name: cargo audit
        description: Check for security vulnerabilities
        entry: cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2023-0071
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-push]
